from fastapi import APIRouter
import uuid
from datetime import datetime, timezone, timedelta
from db import db

router = APIRouter()


@router.post("/seed")
async def seed_database():
    """Seed database with demo data"""
    await db.jobs.delete_many({})
    await db.learning_modules.delete_many({})
    await db.beneficiaires.delete_many({})

    demo_jobs = [
        {"id": str(uuid.uuid4()), "title": "Assistant Administratif", "company": "TechCorp France", "location": "Paris, France", "contract_type": "CDI", "salary_range": "28 000 - 35 000", "required_skills": ["Gestion administrative", "Excel", "Communication", "Organisation"], "description": "Nous recherchons un assistant administratif polyvalent pour rejoindre notre equipe.", "sector": "Administration", "status": "active", "created_at": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Charge de Clientele", "company": "ServicePlus", "location": "Lyon, France", "contract_type": "CDI", "salary_range": "32 000 - 40 000", "required_skills": ["Relation client", "Negociation", "CRM", "Ecoute active"], "description": "Rejoignez notre equipe commerciale en tant que charge de clientele.", "sector": "Commerce", "status": "active", "created_at": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Gestionnaire de Paie", "company": "Fiduciaire Nationale", "location": "Bordeaux, France", "contract_type": "CDI", "salary_range": "35 000 - 45 000", "required_skills": ["Paie", "Droit social", "SILAE", "Excel avance"], "description": "Expert en paie recherche pour cabinet comptable en pleine croissance.", "sector": "Comptabilite", "status": "active", "created_at": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Developpeur Web Junior", "company": "DigitalStart", "location": "Nantes, France", "contract_type": "CDI", "salary_range": "30 000 - 38 000", "required_skills": ["JavaScript", "HTML/CSS", "React", "Git"], "description": "Opportunite pour developpeur junior motive dans une startup innovante.", "sector": "Informatique", "status": "active", "created_at": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "title": "Responsable Formation", "company": "FormaPro Institute", "location": "Toulouse, France", "contract_type": "CDI", "salary_range": "40 000 - 50 000", "required_skills": ["Ingenierie pedagogique", "Management", "Gestion de projet", "Formation adultes"], "description": "Pilotez notre departement formation et accompagnez le developpement des competences.", "sector": "Formation", "status": "active", "created_at": datetime.now(timezone.utc).isoformat()},
    ]

    demo_modules = [
        {"id": str(uuid.uuid4()), "title": "Maitriser Excel pour la Gestion", "description": "Apprenez les fonctions avancees d'Excel.", "duration": "12 heures", "level": "Intermediaire", "skills_developed": ["Excel", "Tableaux croises", "Formules avancees"], "category": "Bureautique"},
        {"id": str(uuid.uuid4()), "title": "Communication Professionnelle", "description": "Developpez vos competences en communication.", "duration": "8 heures", "level": "Debutant", "skills_developed": ["Communication", "Redaction", "Presentation"], "category": "Soft Skills"},
        {"id": str(uuid.uuid4()), "title": "Gestion de Projet Agile", "description": "Initiez-vous aux methodes agiles.", "duration": "16 heures", "level": "Intermediaire", "skills_developed": ["Gestion de projet", "Scrum", "Kanban"], "category": "Management"},
        {"id": str(uuid.uuid4()), "title": "Initiation au Developpement Web", "description": "Decouvrez les bases de HTML, CSS et JavaScript.", "duration": "20 heures", "level": "Debutant", "skills_developed": ["HTML/CSS", "JavaScript", "Git"], "category": "Informatique"},
        {"id": str(uuid.uuid4()), "title": "Droit du Travail Essentiel", "description": "Comprenez les fondamentaux du droit social.", "duration": "10 heures", "level": "Intermediaire", "skills_developed": ["Droit social", "Contrats", "Reglementation"], "category": "Juridique"},
    ]

    await db.jobs.insert_many(demo_jobs)
    await db.learning_modules.insert_many(demo_modules)

    await db.emerging_skills.delete_many({})
    await db.sector_trends.delete_many({})
    await db.skill_contributions.delete_many({})

    demo_emerging_skills = [
        {"id": str(uuid.uuid4()), "skill_name": "Prompt Engineering", "description": "Conception et optimisation de prompts pour l'IA generative", "related_sectors": ["Informatique", "Marketing", "Communication"], "related_jobs": ["Developpeur IA", "Content Manager", "Data Analyst"], "related_tools": ["ChatGPT", "Claude", "Midjourney"], "emergence_score": 0.92, "growth_rate": 0.45, "mention_count": 156, "contributor_count": 89, "status": "emergente", "first_detected": datetime.now(timezone.utc).isoformat(), "last_updated": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "skill_name": "No-Code / Low-Code", "description": "Creation d'applications sans programmation traditionnelle", "related_sectors": ["Informatique", "Administration", "PME"], "related_jobs": ["Business Analyst", "Chef de projet", "Responsable digital"], "related_tools": ["Bubble", "Webflow", "Airtable", "Notion"], "emergence_score": 0.85, "growth_rate": 0.38, "mention_count": 234, "contributor_count": 112, "status": "en_croissance", "first_detected": datetime.now(timezone.utc).isoformat(), "last_updated": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "skill_name": "Green IT", "description": "Pratiques informatiques eco-responsables et durables", "related_sectors": ["Informatique", "Environnement", "Industrie"], "related_jobs": ["Responsable RSE", "Architecte SI", "Chef de projet IT"], "related_tools": ["Cloud Carbon Footprint", "Green Algorithms"], "emergence_score": 0.78, "growth_rate": 0.28, "mention_count": 98, "contributor_count": 45, "status": "emergente", "first_detected": datetime.now(timezone.utc).isoformat(), "last_updated": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "skill_name": "Data Storytelling", "description": "Communication narrative basee sur l'analyse de donnees", "related_sectors": ["Marketing", "Communication", "Conseil"], "related_jobs": ["Data Analyst", "Consultant", "Responsable marketing"], "related_tools": ["Tableau", "Power BI", "Looker"], "emergence_score": 0.72, "growth_rate": 0.25, "mention_count": 187, "contributor_count": 78, "status": "en_croissance", "first_detected": datetime.now(timezone.utc).isoformat(), "last_updated": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "skill_name": "Cybersecurite operationnelle", "description": "Protection des systemes et gestion des incidents de securite", "related_sectors": ["Informatique", "Banque", "Sante"], "related_jobs": ["Analyste SOC", "RSSI", "Pentester"], "related_tools": ["SIEM", "EDR", "Firewall NextGen"], "emergence_score": 0.88, "growth_rate": 0.35, "mention_count": 312, "contributor_count": 134, "status": "en_croissance", "first_detected": datetime.now(timezone.utc).isoformat(), "last_updated": datetime.now(timezone.utc).isoformat()},
    ]

    demo_sector_trends = [
        {"id": str(uuid.uuid4()), "sector_name": "Informatique", "emerging_skills": ["Prompt Engineering", "No-Code", "Green IT", "Cybersecurite"], "declining_skills": ["Flash", "COBOL", "jQuery"], "stable_skills": ["Python", "JavaScript", "SQL", "Git"], "transformation_index": 0.82, "hiring_trend": "croissance", "skill_gap_alert": True, "predicted_skills_demand": [{"skill": "IA Generative", "demand_change": "+45%", "horizon": "2025"}, {"skill": "Cloud Native", "demand_change": "+32%", "horizon": "2025"}, {"skill": "DevSecOps", "demand_change": "+28%", "horizon": "2025"}], "last_updated": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "sector_name": "Administration", "emerging_skills": ["No-Code", "Automatisation", "IA bureautique"], "declining_skills": ["Stenographie", "Classement papier"], "stable_skills": ["Excel", "Redaction", "Organisation", "Accueil"], "transformation_index": 0.58, "hiring_trend": "stable", "skill_gap_alert": False, "predicted_skills_demand": [{"skill": "Outils collaboratifs", "demand_change": "+25%", "horizon": "2025"}, {"skill": "GED", "demand_change": "+18%", "horizon": "2025"}], "last_updated": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "sector_name": "Commerce", "emerging_skills": ["Social Selling", "CRM avance", "Data Analytics"], "declining_skills": ["Vente terrain classique"], "stable_skills": ["Negociation", "Relation client", "Prospection"], "transformation_index": 0.65, "hiring_trend": "croissance", "skill_gap_alert": True, "predicted_skills_demand": [{"skill": "E-commerce", "demand_change": "+35%", "horizon": "2025"}, {"skill": "Marketing automation", "demand_change": "+30%", "horizon": "2025"}], "last_updated": datetime.now(timezone.utc).isoformat()},
    ]

    await db.emerging_skills.insert_many(demo_emerging_skills)
    await db.sector_trends.insert_many(demo_sector_trends)

    await db.job_evolution_indices.delete_many({})
    await db.sector_evolution_indices.delete_many({})

    demo_job_indices = [
        {"id": str(uuid.uuid4()), "job_name": "Assistant Administratif", "sector": "Administration", "evolution_index": 58.0, "index_level": "en_transformation", "new_skills_count": 5, "skill_frequency_score": 0.62, "task_evolution_score": 0.55, "new_tools_score": 0.68, "job_posting_evolution": 0.45, "declining_skills_count": 2, "emerging_skills": ["Outils collaboratifs", "GED", "No-Code", "IA bureautique"], "stable_skills": ["Excel", "Redaction", "Organisation", "Accueil"], "declining_skills": ["Stenographie", "Classement papier"], "recommended_skills": ["Teams/Slack", "Notion", "Automatisation"], "recommended_trainings": ["Maitriser les outils collaboratifs", "Introduction a l'automatisation"], "job_passerelles": ["Office Manager", "Gestionnaire de projet", "Charge de clientele"], "last_calculated": datetime.now(timezone.utc).isoformat(), "data_sources": ["contributions", "offres_emploi", "experts"], "confidence_level": 0.85},
        {"id": str(uuid.uuid4()), "job_name": "Developpeur Web", "sector": "Informatique", "evolution_index": 82.0, "index_level": "forte_mutation", "new_skills_count": 12, "skill_frequency_score": 0.88, "task_evolution_score": 0.78, "new_tools_score": 0.92, "job_posting_evolution": 0.75, "declining_skills_count": 4, "emerging_skills": ["IA Generative", "Prompt Engineering", "No-Code", "Cloud Native", "DevSecOps"], "stable_skills": ["JavaScript", "Git", "API REST", "SQL"], "declining_skills": ["jQuery", "Flash", "PHP legacy"], "recommended_skills": ["React/Vue", "TypeScript", "Docker", "CI/CD", "GPT API"], "recommended_trainings": ["Integration IA Generative", "DevOps moderne", "Architecture Cloud"], "job_passerelles": ["Lead Developer", "Architecte logiciel", "Product Owner technique"], "last_calculated": datetime.now(timezone.utc).isoformat(), "data_sources": ["contributions", "offres_emploi", "experts", "github_trends"], "confidence_level": 0.92},
        {"id": str(uuid.uuid4()), "job_name": "Charge de Clientele", "sector": "Commerce", "evolution_index": 65.0, "index_level": "en_transformation", "new_skills_count": 6, "skill_frequency_score": 0.58, "task_evolution_score": 0.62, "new_tools_score": 0.72, "job_posting_evolution": 0.55, "declining_skills_count": 1, "emerging_skills": ["Social Selling", "CRM avance", "Data Analytics", "Visio-commerce"], "stable_skills": ["Negociation", "Relation client", "Ecoute active", "Prospection"], "declining_skills": ["Vente terrain classique"], "recommended_skills": ["LinkedIn Sales Navigator", "Salesforce", "Analytics client"], "recommended_trainings": ["Social Selling avance", "CRM et automatisation commerciale"], "job_passerelles": ["Key Account Manager", "Responsable commercial", "Customer Success Manager"], "last_calculated": datetime.now(timezone.utc).isoformat(), "data_sources": ["contributions", "offres_emploi"], "confidence_level": 0.78},
        {"id": str(uuid.uuid4()), "job_name": "Gestionnaire de Paie", "sector": "Comptabilite", "evolution_index": 48.0, "index_level": "evolutif", "new_skills_count": 3, "skill_frequency_score": 0.42, "task_evolution_score": 0.45, "new_tools_score": 0.55, "job_posting_evolution": 0.38, "declining_skills_count": 1, "emerging_skills": ["DSN automatisee", "SIRH integre", "Paie dematerialisee"], "stable_skills": ["Droit social", "Paie", "SILAE", "Excel avance"], "declining_skills": ["Paie manuelle"], "recommended_skills": ["Cegid", "ADP", "Parametrage DSN"], "recommended_trainings": ["Evolutions reglementaires 2025", "SIRH avance"], "job_passerelles": ["Responsable paie", "RH generaliste", "Consultant SIRH"], "last_calculated": datetime.now(timezone.utc).isoformat(), "data_sources": ["contributions", "offres_emploi"], "confidence_level": 0.82},
        {"id": str(uuid.uuid4()), "job_name": "Artisan Boulanger", "sector": "Artisanat", "evolution_index": 15.0, "index_level": "stable", "new_skills_count": 1, "skill_frequency_score": 0.12, "task_evolution_score": 0.15, "new_tools_score": 0.18, "job_posting_evolution": 0.10, "declining_skills_count": 0, "emerging_skills": ["Vente en ligne"], "stable_skills": ["Petrissage", "Fermentation", "Cuisson", "Hygiene alimentaire"], "declining_skills": [], "recommended_skills": ["Gestion de commerce", "Reseaux sociaux"], "recommended_trainings": ["Gestion d'entreprise artisanale"], "job_passerelles": ["Chef boulanger", "Formateur metiers de bouche"], "last_calculated": datetime.now(timezone.utc).isoformat(), "data_sources": ["experts"], "confidence_level": 0.75},
        {"id": str(uuid.uuid4()), "job_name": "Analyste Cybersecurite", "sector": "Informatique", "evolution_index": 88.0, "index_level": "forte_mutation", "new_skills_count": 15, "skill_frequency_score": 0.92, "task_evolution_score": 0.85, "new_tools_score": 0.95, "job_posting_evolution": 0.88, "declining_skills_count": 2, "emerging_skills": ["IA defensive", "Zero Trust", "Cloud Security", "DevSecOps", "Threat Intelligence"], "stable_skills": ["Firewall", "SIEM", "Incident Response", "Pentest"], "declining_skills": ["Antivirus traditionnel", "Securite perimetrique"], "recommended_skills": ["XDR/EDR", "SOAR", "Container Security"], "recommended_trainings": ["Certification CISSP", "Cloud Security Architecture", "IA et Cybersecurite"], "job_passerelles": ["RSSI", "Architecte Securite", "Consultant Cyber"], "last_calculated": datetime.now(timezone.utc).isoformat(), "data_sources": ["contributions", "offres_emploi", "experts", "certifications"], "confidence_level": 0.95},
    ]

    demo_sector_indices = [
        {"id": str(uuid.uuid4()), "sector_name": "Informatique", "evolution_index": 78.0, "index_level": "en_transformation", "jobs_count": 25, "jobs_in_transformation": 18, "jobs_stable": 3, "jobs_emerging": 4, "top_emerging_skills": [{"skill": "IA Generative", "growth": "+145%"}, {"skill": "Cloud Native", "growth": "+68%"}, {"skill": "DevSecOps", "growth": "+52%"}], "top_declining_skills": [{"skill": "jQuery", "decline": "-35%"}, {"skill": "Flash", "decline": "-90%"}], "skill_gap_areas": ["Cybersecurite", "IA", "Cloud"], "hiring_trend": "croissance", "innovation_intensity": 0.92, "predicted_evolution_6m": 82.0, "predicted_evolution_12m": 85.0, "last_updated": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "sector_name": "Administration", "evolution_index": 52.0, "index_level": "en_transformation", "jobs_count": 15, "jobs_in_transformation": 8, "jobs_stable": 6, "jobs_emerging": 1, "top_emerging_skills": [{"skill": "Outils collaboratifs", "growth": "+45%"}, {"skill": "GED", "growth": "+32%"}, {"skill": "Automatisation", "growth": "+28%"}], "top_declining_skills": [{"skill": "Classement papier", "decline": "-40%"}], "skill_gap_areas": ["Numerique", "Automatisation"], "hiring_trend": "stable", "innovation_intensity": 0.55, "predicted_evolution_6m": 55.0, "predicted_evolution_12m": 58.0, "last_updated": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "sector_name": "Commerce", "evolution_index": 62.0, "index_level": "en_transformation", "jobs_count": 20, "jobs_in_transformation": 12, "jobs_stable": 6, "jobs_emerging": 2, "top_emerging_skills": [{"skill": "Social Selling", "growth": "+55%"}, {"skill": "E-commerce", "growth": "+42%"}, {"skill": "Data Analytics", "growth": "+38%"}], "top_declining_skills": [{"skill": "Vente terrain", "decline": "-25%"}], "skill_gap_areas": ["Digital", "Analytics"], "hiring_trend": "croissance", "innovation_intensity": 0.68, "predicted_evolution_6m": 65.0, "predicted_evolution_12m": 70.0, "last_updated": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "sector_name": "Artisanat", "evolution_index": 18.0, "index_level": "stable", "jobs_count": 30, "jobs_in_transformation": 2, "jobs_stable": 27, "jobs_emerging": 1, "top_emerging_skills": [{"skill": "Vente en ligne", "growth": "+22%"}, {"skill": "Reseaux sociaux", "growth": "+18%"}], "top_declining_skills": [], "skill_gap_areas": ["Digital"], "hiring_trend": "stable", "innovation_intensity": 0.15, "predicted_evolution_6m": 20.0, "predicted_evolution_12m": 22.0, "last_updated": datetime.now(timezone.utc).isoformat()},
    ]

    await db.job_evolution_indices.insert_many(demo_job_indices)
    await db.sector_evolution_indices.insert_many(demo_sector_indices)

    await db.ubuntoo_exchanges.delete_many({})
    await db.ubuntoo_signals.delete_many({})
    await db.ubuntoo_insights.delete_many({})

    demo_ubuntoo_exchanges = [
        {"id": str(uuid.uuid4()), "exchange_type": "retour_experience", "group": "numerique", "title": "L'IA dans mon quotidien", "content_summary": "Depuis 6 mois, j'utilise ChatGPT quotidiennement pour rediger mes rapports.", "author": "Marie D.", "detected_skills": ["Prompt Engineering", "IA Generative", "Formation interne"], "detected_tools": ["ChatGPT", "GPT-4"], "detected_practices": ["Automatisation de la redaction"], "related_jobs": ["Assistant Administratif"], "related_sectors": ["Administration"], "author_role": "professionnel", "likes": 12, "replies_count": 3, "timestamp": (datetime.now(timezone.utc) - timedelta(days=2)).isoformat()},
        {"id": str(uuid.uuid4()), "exchange_type": "discussion", "group": "reconversion", "title": "Centralisation des outils RH", "content_summary": "Notre service RH a remplace 3 outils par une seule plateforme SIRH integree.", "author": "Philippe R.", "detected_skills": ["SIRH integre", "Parametrage logiciel"], "detected_tools": ["SIRH", "Cegid"], "detected_practices": ["Centralisation des outils"], "related_jobs": ["Gestionnaire de Paie"], "related_sectors": ["Comptabilite"], "author_role": "professionnel", "likes": 8, "replies_count": 5, "timestamp": (datetime.now(timezone.utc) - timedelta(days=5)).isoformat()},
        {"id": str(uuid.uuid4()), "exchange_type": "mentorat", "group": "numerique", "title": "Productivite des juniors avec l'IA", "content_summary": "Les juniors qui maitrisent les assistants de code IA sont 2 fois plus productifs.", "author": "Jean-Pierre M.", "detected_skills": ["IA assistee au code", "Pair programming IA"], "detected_tools": ["GitHub Copilot", "Cursor"], "detected_practices": ["Developpement assiste par IA"], "related_jobs": ["Developpeur Web"], "related_sectors": ["Informatique"], "author_role": "mentor", "likes": 24, "replies_count": 7, "timestamp": (datetime.now(timezone.utc) - timedelta(days=3)).isoformat()},
        {"id": str(uuid.uuid4()), "exchange_type": "discussion", "group": "reconversion", "title": "Social selling sur LinkedIn", "content_summary": "Le social selling sur LinkedIn est devenu incontournable.", "author": "Lucas T.", "detected_skills": ["Social Selling", "Personal Branding"], "detected_tools": ["LinkedIn Sales Navigator"], "detected_practices": ["Prospection sur reseaux sociaux"], "related_jobs": ["Charge de Clientele"], "related_sectors": ["Commerce"], "author_role": "professionnel", "likes": 15, "replies_count": 4, "timestamp": (datetime.now(timezone.utc) - timedelta(days=7)).isoformat()},
        {"id": str(uuid.uuid4()), "exchange_type": "question", "group": "numerique", "title": "Cybersecurite et cloud", "content_summary": "Comment gerer la cybersecurite quand on passe au full cloud ?", "author": "Sarah M.", "detected_skills": ["Cloud Security", "Security Champion"], "detected_tools": ["AWS Security Hub"], "detected_practices": ["Security by design"], "related_jobs": ["Analyste Cybersecurite"], "related_sectors": ["Informatique"], "author_role": "professionnel", "likes": 6, "replies_count": 2, "timestamp": (datetime.now(timezone.utc) - timedelta(days=1)).isoformat()},
        {"id": str(uuid.uuid4()), "exchange_type": "aide", "group": "handicap", "title": "Amenagement poste de travail", "content_summary": "Quelles aides pour amenager un poste de travail en teletravail pour une personne en situation de handicap ?", "author": "Thomas L.", "detected_skills": ["Ergonomie", "Droit du travail handicap"], "detected_tools": ["AGEFIPH"], "detected_practices": ["Amenagement raisonnable"], "related_jobs": ["RH"], "related_sectors": ["Ressources Humaines"], "author_role": "professionnel", "likes": 9, "replies_count": 6, "timestamp": (datetime.now(timezone.utc) - timedelta(days=4)).isoformat()},
        {"id": str(uuid.uuid4()), "exchange_type": "retour_experience", "group": "vsi", "title": "Valoriser son benevolat", "content_summary": "Comment j'ai valorise mes 5 ans de benevolat associatif pour decrocher un poste en ESS.", "author": "Pierre D.", "detected_skills": ["Valorisation des acquis", "Communication"], "detected_tools": [], "detected_practices": ["Bilan de competences informel"], "related_jobs": ["Coordinateur ESS"], "related_sectors": ["Economie Sociale"], "author_role": "professionnel", "likes": 18, "replies_count": 8, "timestamp": (datetime.now(timezone.utc) - timedelta(days=6)).isoformat()},
    ]

    demo_ubuntoo_signals = [
        {"id": str(uuid.uuid4()), "signal_type": "competence_emergente", "name": "Prompt Engineering", "description": "Competence de redaction et optimisation de prompts pour les IA generatives.", "mention_count": 47, "first_detected": (datetime.now(timezone.utc) - timedelta(days=60)).isoformat(), "last_detected": (datetime.now(timezone.utc) - timedelta(days=1)).isoformat(), "related_jobs": ["Assistant Administratif", "Developpeur Web"], "related_sectors": ["Administration", "Informatique"], "source_exchanges_count": 32, "trend_direction": "hausse", "growth_rate": 0.85, "validation_status": "integree", "ai_confidence": 0.95, "ai_analysis": {"category": "technique", "impact": "transversal"}, "linked_observatory_skills": ["Prompt Engineering"], "linked_evolution_jobs": ["Assistant Administratif", "Developpeur Web"], "created_at": (datetime.now(timezone.utc) - timedelta(days=60)).isoformat()},
        {"id": str(uuid.uuid4()), "signal_type": "nouvel_outil", "name": "Assistants de code IA", "description": "Outils comme GitHub Copilot et Cursor qui transforment la pratique du developpement.", "mention_count": 38, "first_detected": (datetime.now(timezone.utc) - timedelta(days=45)).isoformat(), "last_detected": (datetime.now(timezone.utc) - timedelta(days=2)).isoformat(), "related_jobs": ["Developpeur Web"], "related_sectors": ["Informatique"], "source_exchanges_count": 25, "trend_direction": "hausse", "growth_rate": 0.72, "validation_status": "validee_humain", "ai_confidence": 0.91, "linked_observatory_skills": [], "linked_evolution_jobs": ["Developpeur Web"], "created_at": (datetime.now(timezone.utc) - timedelta(days=45)).isoformat()},
        {"id": str(uuid.uuid4()), "signal_type": "pratique_nouvelle", "name": "Citizen Development (No-Code)", "description": "Les fonctions support creent leurs propres outils grace aux plateformes no-code.", "mention_count": 29, "first_detected": (datetime.now(timezone.utc) - timedelta(days=40)).isoformat(), "last_detected": (datetime.now(timezone.utc) - timedelta(days=3)).isoformat(), "related_jobs": ["Assistant Administratif"], "related_sectors": ["Administration"], "source_exchanges_count": 18, "trend_direction": "hausse", "growth_rate": 0.55, "validation_status": "analysee_ia", "ai_confidence": 0.82, "linked_observatory_skills": ["No-Code / Low-Code"], "linked_evolution_jobs": ["Assistant Administratif"], "created_at": (datetime.now(timezone.utc) - timedelta(days=40)).isoformat()},
        {"id": str(uuid.uuid4()), "signal_type": "transformation_metier", "name": "Vente hybride terrain/digital", "description": "Les commerciaux evoluent vers un modele hybride digital.", "mention_count": 22, "first_detected": (datetime.now(timezone.utc) - timedelta(days=50)).isoformat(), "last_detected": (datetime.now(timezone.utc) - timedelta(days=5)).isoformat(), "related_jobs": ["Charge de Clientele"], "related_sectors": ["Commerce"], "source_exchanges_count": 15, "trend_direction": "hausse", "growth_rate": 0.48, "validation_status": "validee_humain", "ai_confidence": 0.88, "linked_observatory_skills": ["Social Selling"], "linked_evolution_jobs": ["Charge de Clientele"], "created_at": (datetime.now(timezone.utc) - timedelta(days=50)).isoformat()},
    ]

    demo_ubuntoo_insights = [
        {"id": str(uuid.uuid4()), "insight_type": "tendance_emergente", "title": "L'IA generative transforme tous les metiers tertiaires", "description": "Adoption massive des outils d'IA generative bien au-dela du secteur IT.", "supporting_signals": ["Prompt Engineering", "Assistants de code IA"], "impacted_jobs": ["Assistant Administratif", "Developpeur Web"], "impacted_sectors": ["Administration", "Informatique"], "recommendation": "Integrer des modules de formation IA generative dans tous les parcours.", "priority": "haute", "created_at": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "insight_type": "alerte_competence", "title": "Acceleration de l'obsolescence dans la gestion de paie", "description": "La digitalisation de la paie s'accelere plus vite que prevu.", "supporting_signals": ["Obsolescence des competences paie manuelles"], "impacted_jobs": ["Gestionnaire de Paie"], "impacted_sectors": ["Comptabilite"], "recommendation": "Anticiper la montee en competences SIRH.", "priority": "haute", "created_at": datetime.now(timezone.utc).isoformat()},
        {"id": str(uuid.uuid4()), "insight_type": "opportunite_formation", "title": "Le No-Code comme levier d'autonomie professionnelle", "description": "Les professionnels qui maitrisent le no-code gagnent en valeur.", "supporting_signals": ["Citizen Development (No-Code)"], "impacted_jobs": ["Assistant Administratif", "Office Manager"], "impacted_sectors": ["Administration"], "recommendation": "Creer un parcours Autonomie numerique centre sur le no-code.", "priority": "moyenne", "created_at": datetime.now(timezone.utc).isoformat()},
    ]

    await db.ubuntoo_exchanges.insert_many(demo_ubuntoo_exchanges)
    await db.ubuntoo_signals.insert_many(demo_ubuntoo_signals)
    await db.ubuntoo_insights.insert_many(demo_ubuntoo_insights)

    return {
        "message": "Base de donnees initialisee",
        "jobs": len(demo_jobs),
        "modules": len(demo_modules),
        "emerging_skills": len(demo_emerging_skills),
        "sector_trends": len(demo_sector_trends),
        "job_indices": len(demo_job_indices),
        "sector_indices": len(demo_sector_indices),
        "ubuntoo_exchanges": len(demo_ubuntoo_exchanges),
        "ubuntoo_signals": len(demo_ubuntoo_signals),
        "ubuntoo_insights": len(demo_ubuntoo_insights),
    }


@router.get("/")
async def root():
    return {"message": "Re'Actif Pro API", "version": "2.0.0"}
